// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"api/pkg/api"
	"api/pkg/api/handlers"
	"api/pkg/client"
	"api/pkg/config"
)

// Injectors from wire.go:

func InitializeApi(c *config.Config) (*api.Server, error) {
	authServiceClient, err := auth.InitClient(c)
	if err != nil {
		return nil, err
	}
	authClient := auth.NewAuthServiceClient(authServiceClient)
	authHandler := handlers.NewAuthHandler(authClient)
	videoServiceClient, err := auth.InitVideoClient(c)
	if err != nil {
		return nil, err
	}
	videoClient := auth.NewVideoClient(videoServiceClient)
	videoHandler := handlers.NewVideoHandler(videoClient)
	server, err := api.NewserverHttp(c, authHandler, videoHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
